# from ..base import factoryCls
from .viz import Viz, plotly_google_colab, enable_plotly_in_cell, disable_plotly_in_cell, vizGet
from .pandasNewMethodsPlots import *
from .plotlyNewMethodsPlots import *
from .studyviz_datasclassif import Study_DatasClassif_Viz
from .studyviz_datasuperviseclassif import Study_DatasSuperviseClassif_Viz
from .studyviz_cvresultatsclassif import Study_CvResultatsClassif_Viz
from .studyviz_basesuperviseclassif import Study_BaseSuperviseClassif_Viz
# from .studyviz_basesuperviseproject import Study_BaseSuperviseProject_Viz
from .studyviz_studyclassif_ import Study_StudyClassif__Viz
from .studyviz_studyclassif import Study_StudyClassif_Viz
from .studyviz_studyclassifproject import Study_StudyClassifProject_Viz
from .studyviz_cviclassif import Study_CVIClassif_Viz
from .studyviz_crossvaliditem import Study_CrossValidItem_Viz
from .sameErrors import sameErrorsViz
from .studyviz_tuned import Study_Tuned_Viz